//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DownloadManager.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string Common_add {
            get {
                return ResourceManager.GetString("Common_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        public static string Common_remove {
            get {
                return ResourceManager.GetString("Common_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove all.
        /// </summary>
        public static string Common_remove_all {
            get {
                return ResourceManager.GetString("Common_remove_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retry.
        /// </summary>
        public static string Common_retry {
            get {
                return ResourceManager.GetString("Common_retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string Common_select {
            get {
                return ResourceManager.GetString("Common_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select all.
        /// </summary>
        public static string Common_select_all {
            get {
                return ResourceManager.GetString("Common_select_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start.
        /// </summary>
        public static string Common_start {
            get {
                return ResourceManager.GetString("Common_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start all.
        /// </summary>
        public static string Common_start_all {
            get {
                return ResourceManager.GetString("Common_start_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        public static string Common_stop {
            get {
                return ResourceManager.GetString("Common_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop all.
        /// </summary>
        public static string Common_stop_all {
            get {
                return ResourceManager.GetString("Common_stop_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to archive.
        /// </summary>
        public static string CommonTitles_Archive {
            get {
                return ResourceManager.GetString("CommonTitles_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloads.
        /// </summary>
        public static string CommonTitles_Downloads {
            get {
                return ResourceManager.GetString("CommonTitles_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExtendedStatusToText_Canceled {
            get {
                return ResourceManager.GetString("ExtendedStatusToText_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExtendedStatusToText_Completed {
            get {
                return ResourceManager.GetString("ExtendedStatusToText_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExtendedStatusToText_Failed {
            get {
                return ResourceManager.GetString("ExtendedStatusToText_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExtendedStatusToText_FailedServer {
            get {
                return ResourceManager.GetString("ExtendedStatusToText_FailedServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExtendedStatusToText_None {
            get {
                return ResourceManager.GetString("ExtendedStatusToText_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m confused :S.
        /// </summary>
        public static string ExtendedStatusToText_Null {
            get {
                return ResourceManager.GetString("ExtendedStatusToText_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExtendedStatusToText_Paused {
            get {
                return ResourceManager.GetString("ExtendedStatusToText_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExtendedStatusToText_Queued {
            get {
                return ResourceManager.GetString("ExtendedStatusToText_Queued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExtendedStatusToText_Transferring {
            get {
                return ResourceManager.GetString("ExtendedStatusToText_Transferring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExtendedStatusToText_Waiting {
            get {
                return ResourceManager.GetString("ExtendedStatusToText_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExtendedStatusToText_WaitingForExternalPower {
            get {
                return ResourceManager.GetString("ExtendedStatusToText_WaitingForExternalPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExtendedStatusToText_WaitingForExternalPowerDueToBatterySaverMode {
            get {
                return ResourceManager.GetString("ExtendedStatusToText_WaitingForExternalPowerDueToBatterySaverMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExtendedStatusToText_WaitingForNonVoiceBlockingNetwork {
            get {
                return ResourceManager.GetString("ExtendedStatusToText_WaitingForNonVoiceBlockingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExtendedStatusToText_WaitingForRetry {
            get {
                return ResourceManager.GetString("ExtendedStatusToText_WaitingForRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExtendedStatusToText_WaitingForWiFi {
            get {
                return ResourceManager.GetString("ExtendedStatusToText_WaitingForWiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To retry the download, tap and hold, then tap Retry..
        /// </summary>
        public static string TapMessage_Canceled {
            get {
                return ResourceManager.GetString("TapMessage_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The download ha been completed successfully..
        /// </summary>
        public static string TapMessage_Completed {
            get {
                return ResourceManager.GetString("TapMessage_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TapMessage_Failed {
            get {
                return ResourceManager.GetString("TapMessage_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TapMessage_FailedServer {
            get {
                return ResourceManager.GetString("TapMessage_FailedServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start the download, tap and hold, then tap Start..
        /// </summary>
        public static string TapMessage_None {
            get {
                return ResourceManager.GetString("TapMessage_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TapMessage_Paused {
            get {
                return ResourceManager.GetString("TapMessage_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TapMessage_Queued {
            get {
                return ResourceManager.GetString("TapMessage_Queued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TapMessage_Transferring {
            get {
                return ResourceManager.GetString("TapMessage_Transferring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TapMessage_Waiting {
            get {
                return ResourceManager.GetString("TapMessage_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TapMessage_WaitingForExternalPower {
            get {
                return ResourceManager.GetString("TapMessage_WaitingForExternalPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TapMessage_WaitingForExternalPowerDueToBatterySaverMode {
            get {
                return ResourceManager.GetString("TapMessage_WaitingForExternalPowerDueToBatterySaverMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TapMessage_WaitingForNonVoiceBlockingNetwork {
            get {
                return ResourceManager.GetString("TapMessage_WaitingForNonVoiceBlockingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TapMessage_WaitingForRetry {
            get {
                return ResourceManager.GetString("TapMessage_WaitingForRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TapMessage_WaitingForWiFi {
            get {
                return ResourceManager.GetString("TapMessage_WaitingForWiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WarningMessage_remove_all {
            get {
                return ResourceManager.GetString("WarningMessage_remove_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WarningMessage_remove_selected {
            get {
                return ResourceManager.GetString("WarningMessage_remove_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WarningMessage_remove_single {
            get {
                return ResourceManager.GetString("WarningMessage_remove_single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WarningTitle_remove_all {
            get {
                return ResourceManager.GetString("WarningTitle_remove_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WarningTitle_remove_selected {
            get {
                return ResourceManager.GetString("WarningTitle_remove_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WarningTitle_remove_single {
            get {
                return ResourceManager.GetString("WarningTitle_remove_single", resourceCulture);
            }
        }
    }
}
